/-
The crystal cocycle lemmas of the LCC/BC transport (LEARNINGS #82) and the
B1 G_log rigidity follow-on (LEARNINGS #86).

## What this module is

The Lean side of `docs/03_research/lcc_bc_transport.md` section 1.3 (Lemmas 1
and 2) and section 6 (the VERIFIER handoff V1-V3), plus the open target V4 from
`docs/03_research/b1_glog_rigidity.md`. The mathematical context:

The Lonely Crystal Conjecture (LCC, LEARNINGS #76) cone of positive
log-crystals was transported through the Bost-Connes uniqueness template
(LEARNINGS #81). Two elementary facts carry the whole discrete leg:

  Lemma 1 (V2): the literal BC quasi-invariance axiom on a comb
  `c : ℕ → ℝ`, namely `c (m * n) = m^(-β) * c n`, collapses the comb to
  the flat ray `c n = c 1 * n^(-β)` (the comb of `ζ(s)`, the WRONG ray:
  the named failure of the literal transport). The prime-generated form
  suffices, by induction along the factorization.

  Lemma 2 (V1): the repaired condition lives one Moebius twist up. With
  `B = 1 * b` the integrated comb (`B n = ∑_{d ∣ n} b d`), the additive
  cocycle identity `B (p * n) - B n = log p` for all primes `p` and all
  `n ≥ 1` holds IFF `b` is the von Mangoldt comb away from the unit atom
  (`b n = Λ n` for `n ≥ 2`, with `b 1` free). This is the exact statement
  that composite pinching = "mixed cumulants vanish" calibrates the crystal
  to `Λ`.

  V3: increment nonnegativity. For `b ≥ 0` the increments
  `B (p * n) - B n` are automatically nonnegative, because the divisors of
  `n` embed into the divisors of `p * n`.

## Status of the targets

  V1  `increments_eq_log_iff_eq_vonMangoldt`   PROVED (sorry-free).
  V2  `flat_ray_of_quasiInvariance` (full semigroup form) and
      `flat_ray_of_prime_quasiInvariance` (prime-generated form)
                                               PROVED (sorry-free).
  V3  `divisorSum_le_divisorSum_mul_of_nonneg` PROVED (sorry-free).
  V4  the G_log dense-translate rigidity lemma (`b1_glog_rigidity.md`):
      ARITHMETIC CORE PROVED (`dense_primeLogSubgroup`, sorry-free): the
      additive subgroup of ℝ generated by `{log 2, log 3}` is dense, which
      is the single prime-dependent step B1 calls "the work" (two primes
      suffice). The remaining measure-theoretic assembly (twist by
      `exp(βx)`, dense-to-full translation invariance, Haar uniqueness) is
      generic and prime-free; documented as the V4-measure gap below, with
      the one missing Mathlib lemma (dense-translation-invariance upgrades
      to full invariance) named. No `sorry` in this file.

  Plus the two unconditional ADVERSARY lemmas (blocks 2-3) as the first
  EF-positivity skeletons, all sorry-free:
    `slope_one_pin`, `slope_one_diverges`   slope-1 lemma (block 2);
    `flat_comb_excluded`, `flat_comb_trough_witness`  flat-comb exclusion
                                            (block 3, the FiniteCertificates
                                            sign certificate).
  These translate the SIGN/asymptotic core of the explicit-formula pairing,
  taking the analytic (EF) identity and Fourier facts (which live as the
  `#EF-*` targets in `ExplicitFormula.lean`) as explicit hypotheses.

The proofs use only Finset divisor-sum manipulation, Mathlib's
`ArithmeticFunction.vonMangoldt_sum` (`∑_{d ∣ n} Λ d = log n`), and a
positive strong-induction principle along minimal prime factors. No zero of
any L-function appears anywhere (K1-clean by construction): the only inputs
are `ℕ`, its divisor lattice, and `Real.log`.

No em dashes anywhere in this file (project style rule).
-/

import Mathlib.NumberTheory.ArithmeticFunction.VonMangoldt
import Mathlib.NumberTheory.Divisors
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Topology.Algebra.Order.Archimedean

namespace ZetaRH.CrystalCocycle

open scoped ArithmeticFunction
open Finset

/-! ### The integrated comb `B = 1 * b` (Dirichlet convolution with `ζ`). -/

/-- The integrated comb: `divisorSum b n = ∑_{d ∣ n} b d`, the Dirichlet
    convolution `(1 * b) n`. This is the `B` of the transport dossier
    (Definition 5 of `lcc_bc_transport.md`); for `b = Λ` it equals `log n`
    by `ArithmeticFunction.vonMangoldt_sum`. -/
noncomputable def divisorSum (b : ℕ → ℝ) (n : ℕ) : ℝ :=
  ∑ d ∈ n.divisors, b d

/-! ### Induction infrastructure.

    Both Lemma 1 (prime-generated form) and Lemma 2 (forward direction) run
    the same induction: every `n ≥ 2` splits off its minimal prime factor,
    so every `n ≥ 1` is reachable from `1` by repeated prime multiplication.
    We package the two ingredients once. -/

/-- Strong induction on the positive naturals: to prove `P n` for all
    `n ≥ 1` it suffices to prove `P n` given `P m` for all `1 ≤ m < n`. -/
theorem pos_strong_induction (P : ℕ → Prop)
    (step : ∀ n : ℕ, 1 ≤ n → (∀ m : ℕ, 1 ≤ m → m < n → P m) → P n) :
    ∀ n : ℕ, 1 ≤ n → P n := by
  have main : ∀ N n : ℕ, n ≤ N → 1 ≤ n → P n := by
    intro N
    induction N with
    | zero => intro n hn h1; omega
    | succ N ih =>
      intro n hn h1
      exact step n h1 fun m hm hmn => ih m (by omega) hm
  intro n hn
  exact main n n le_rfl hn

/-- Every `n > 1` splits as `n = p * q` with `p` prime and `1 ≤ q < n`
    (take `p` to be the minimal prime factor). This is the single
    factorization step that drives the inductions below. -/
theorem exists_prime_mul_eq {n : ℕ} (hn : 1 < n) :
    ∃ p q : ℕ, p.Prime ∧ 1 ≤ q ∧ q < n ∧ n = p * q := by
  have hn1 : n ≠ 1 := by omega
  have hp : (n.minFac).Prime := Nat.minFac_prime hn1
  refine ⟨n.minFac, n / n.minFac, hp, ?_, ?_, ?_⟩
  · have := Nat.div_pos (Nat.minFac_le (by omega)) hp.pos
    omega
  · exact Nat.div_lt_self (by omega) hp.one_lt
  · exact (Nat.mul_div_cancel' (Nat.minFac_dvd n)).symm

/-! ### V2: Lemma 1 (quasi-invariance collapse, the O2 computation).

    The literal BC axiom `c (m * n) = m^(-β) * c n` pins the comb to the
    flat ray `c n = c 1 * n^(-β)`. At `β = 1/2` this is the comb of
    `c 1 * ζ(s)`, full support, NOT the von Mangoldt comb: the sharp
    failure of the literal transport (`lcc_bc_transport.md` Lemma 1). -/

/-- **V2, full-semigroup form.** Quasi-invariance over all of `ℕ×` collapses
    to the flat ray: specialize the hypothesis at `(m, n) = (n, 1)`. -/
theorem flat_ray_of_quasiInvariance (c : ℕ → ℝ) (β : ℝ)
    (h : ∀ m n : ℕ, 1 ≤ m → 1 ≤ n → c (m * n) = (m : ℝ) ^ (-β) * c n) :
    ∀ n : ℕ, 1 ≤ n → c n = c 1 * (n : ℝ) ^ (-β) := by
  intro n hn
  have h1 := h n 1 hn le_rfl
  rw [mul_one] at h1
  rw [h1]
  ring

/-- **V2, prime-generated form.** Quasi-invariance under the prime scaling
    maps alone already collapses to the flat ray, by strong induction along
    the minimal prime factor: every `n ≥ 1` is reachable from `1` by
    repeated prime multiplication, and each step contributes one exact
    cocycle factor `p^(-β)`. -/
theorem flat_ray_of_prime_quasiInvariance (c : ℕ → ℝ) (β : ℝ)
    (h : ∀ p n : ℕ, p.Prime → 1 ≤ n → c (p * n) = (p : ℝ) ^ (-β) * c n) :
    ∀ n : ℕ, 1 ≤ n → c n = c 1 * (n : ℝ) ^ (-β) := by
  refine pos_strong_induction _ fun n h1 ih => ?_
  rcases h1.eq_or_lt with rfl | h2
  · simp
  · obtain ⟨p, q, hp, hq1, hqlt, hq⟩ := exists_prime_mul_eq h2
    have hcq := ih q hq1 hqlt
    calc c n = c (p * q) := by rw [hq]
      _ = (p : ℝ) ^ (-β) * c q := h p q hp hq1
      _ = (p : ℝ) ^ (-β) * (c 1 * (q : ℝ) ^ (-β)) := by rw [hcq]
      _ = c 1 * ((p : ℝ) ^ (-β) * (q : ℝ) ^ (-β)) := by ring
      _ = c 1 * (((p : ℝ) * (q : ℝ)) ^ (-β)) := by
          rw [Real.mul_rpow (Nat.cast_nonneg p) (Nat.cast_nonneg q)]
      _ = c 1 * (n : ℝ) ^ (-β) := by rw [← Nat.cast_mul, ← hq]

/-! ### V3: increment nonnegativity.

    For `b ≥ 0` the integrated comb is monotone under prime multiplication:
    the divisors of `n` embed into the divisors of `p * n`, and the new
    divisors contribute nonnegatively. This is the "automatic" half of the
    cocycle condition (Definition 5 of the dossier). -/

/-- **V3.** If `b ≥ 0` then `B n ≤ B (p * n)` for every prime `p` and
    `n ≥ 1`. (No vanishing-at-0 hypothesis is needed: `0` is never a
    divisor, so `b 0` is invisible to `divisorSum`.) -/
theorem divisorSum_le_divisorSum_mul_of_nonneg (b : ℕ → ℝ)
    (hb : ∀ k : ℕ, 0 ≤ b k) {p : ℕ} (hp : p.Prime) {n : ℕ} (hn : 1 ≤ n) :
    divisorSum b n ≤ divisorSum b (p * n) := by
  simp only [divisorSum]
  refine Finset.sum_le_sum_of_subset_of_nonneg
    (Nat.divisors_subset_of_dvd
      (Nat.mul_ne_zero hp.ne_zero (by omega)) (dvd_mul_left n p))
    fun i _ _ => hb i

/-! ### V1: Lemma 2 (cocycle rigidity equivalence).

    The main content. Three helper lemmas:

      (A) any comb agreeing with `Λ` from 2 on has integrated comb
          `b 1 + log n` (downstream of `vonMangoldt_sum`);
      (B) constant increments `log p` force the integrated comb to be
          `b 1 + log n` (induction along the factorization);
      (C) a comb is determined by its integrated comb (Moebius inversion
          in its cheapest form: strong induction, isolating the top
          divisor `n` against the strictly smaller ones).

    Then V1 composes: increments are `log p` iff the integrated comb is
    `b 1 + log n` iff `b` agrees with `Λ` from 2 on. -/

/-- Helper (A): if `g` agrees with the von Mangoldt function for all
    arguments `≥ 2`, its divisor sum is `g 1 + log n`. The von Mangoldt
    term at `d = 1` is zero, so the unit atom `g 1` rides along freely. -/
theorem divisorSum_eq_add_log_of_eq_vonMangoldt (g : ℕ → ℝ)
    (hg : ∀ m : ℕ, 2 ≤ m → g m = Λ m) {n : ℕ} (hn : 1 ≤ n) :
    divisorSum g n = g 1 + Real.log (n : ℝ) := by
  have h1 : (1 : ℕ) ∈ n.divisors := Nat.one_mem_divisors.mpr (by omega)
  have hsplit : g 1 + ∑ d ∈ n.divisors.erase 1, g d = ∑ d ∈ n.divisors, g d :=
    Finset.add_sum_erase _ g h1
  have htail : ∑ d ∈ n.divisors.erase 1, g d = Real.log (n : ℝ) := by
    have hcong : ∑ d ∈ n.divisors.erase 1, g d
        = ∑ d ∈ n.divisors.erase 1, Λ d := by
      refine Finset.sum_congr rfl fun d hd => ?_
      have hd1 : d ≠ 1 := Finset.ne_of_mem_erase hd
      have hdpos : 0 < d := Nat.pos_of_mem_divisors (Finset.mem_of_mem_erase hd)
      exact hg d (by omega)
    rw [hcong, Finset.sum_erase _ ArithmeticFunction.vonMangoldt_apply_one,
      ArithmeticFunction.vonMangoldt_sum]
  simp only [divisorSum]
  rw [← hsplit, htail]

/-- Helper (B): constant increments `log p` force `B n = b 1 + log n`,
    by strong induction along the minimal prime factor. Each factorization
    step `n = p * q` converts one increment hypothesis into one `log p`,
    and the logs assemble through `Real.log_mul`. -/
theorem divisorSum_eq_add_log_of_increments (b : ℕ → ℝ)
    (h : ∀ p n : ℕ, p.Prime → 1 ≤ n →
      divisorSum b (p * n) - divisorSum b n = Real.log (p : ℝ)) :
    ∀ n : ℕ, 1 ≤ n → divisorSum b n = b 1 + Real.log (n : ℝ) := by
  refine pos_strong_induction _ fun n h1 ih => ?_
  rcases h1.eq_or_lt with rfl | h2
  · simp [divisorSum]
  · obtain ⟨p, q, hp, hq1, hqlt, hq⟩ := exists_prime_mul_eq h2
    have hstep := h p q hp hq1
    rw [← hq] at hstep
    have hqsum := ih q hq1 hqlt
    have hlogn : Real.log (n : ℝ) = Real.log (p : ℝ) + Real.log (q : ℝ) := by
      rw [hq]
      push_cast
      exact Real.log_mul (Nat.cast_ne_zero.mpr hp.ne_zero)
        (Nat.cast_ne_zero.mpr (by omega))
    rw [hlogn]
    linarith

/-- Helper (C): a comb is determined by its integrated comb. This is
    Moebius inversion in its cheapest constructive form: at each `n` the
    divisor sum isolates `b n` against divisors `d < n`, which are handled
    by strong induction. -/
theorem eq_of_divisorSum_eq (g g' : ℕ → ℝ)
    (h : ∀ n : ℕ, 1 ≤ n → divisorSum g n = divisorSum g' n) :
    ∀ n : ℕ, 1 ≤ n → g n = g' n := by
  refine pos_strong_induction _ fun n h1 ih => ?_
  have hn0 : n ≠ 0 := by omega
  have hmem : n ∈ n.divisors := Nat.mem_divisors_self n hn0
  have hsum := h n h1
  simp only [divisorSum] at hsum
  rw [← Finset.add_sum_erase _ g hmem, ← Finset.add_sum_erase _ g' hmem] at hsum
  have htail : ∑ d ∈ n.divisors.erase n, g d
      = ∑ d ∈ n.divisors.erase n, g' d := by
    refine Finset.sum_congr rfl fun d hd => ?_
    have hdn : d ≠ n := Finset.ne_of_mem_erase hd
    have hdmem := Finset.mem_of_mem_erase hd
    have hdpos : 0 < d := Nat.pos_of_mem_divisors hdmem
    have hdle : d ≤ n := Nat.le_of_dvd (by omega) (Nat.mem_divisors.mp hdmem).1
    exact ih d hdpos (by omega)
  rw [htail] at hsum
  linarith

/-- The reference comb: the von Mangoldt comb with the unit atom set to
    `b1`. Lemma 2 leaves the unit atom free (the divisor-sum increments
    never see it), so the rigidity target is this one-parameter family. -/
noncomputable def refComb (b1 : ℝ) : ℕ → ℝ :=
  fun n => if n = 1 then b1 else Λ n

@[simp]
theorem refComb_one (b1 : ℝ) : refComb b1 1 = b1 := by
  simp [refComb]

theorem refComb_of_two_le (b1 : ℝ) {n : ℕ} (hn : 2 ≤ n) :
    refComb b1 n = Λ n := by
  have h1 : n ≠ 1 := by omega
  simp [refComb, h1]

/-- **V1 (Lemma 2, cocycle rigidity equivalence).** With
    `B = divisorSum b` the integrated comb: the additive cocycle identity

      `B (p * n) - B n = log p`  for all primes `p` and all `n ≥ 1`

    holds IFF `b n = Λ n` for all `n ≥ 2` (the unit atom `b 1` stays
    free). Forward: constant increments force `B n = b 1 + log n`
    (helper B), the reference comb `refComb (b 1)` produces the same
    integrated comb (helper A), and combs with equal integrated combs are
    equal (helper C). Reverse: `B n = b 1 + log n` by helper A, and
    `log (p * n) - log n = log p`.

    This is the repaired BC axiom of the transport: the KMS cocycle
    condition on the integrated comb lands exactly on the von Mangoldt
    crystal, where the literal quasi-invariance axiom (V2) lands on the
    flat ray. -/
theorem increments_eq_log_iff_eq_vonMangoldt (b : ℕ → ℝ) :
    (∀ p n : ℕ, p.Prime → 1 ≤ n →
        divisorSum b (p * n) - divisorSum b n = Real.log (p : ℝ)) ↔
      ∀ n : ℕ, 2 ≤ n → b n = Λ n := by
  constructor
  · intro h n hn
    have hB := divisorSum_eq_add_log_of_increments b h
    have hB' : ∀ m : ℕ, 1 ≤ m →
        divisorSum (refComb (b 1)) m = b 1 + Real.log (m : ℝ) := by
      intro m hm
      rw [divisorSum_eq_add_log_of_eq_vonMangoldt (refComb (b 1))
        (fun k hk => refComb_of_two_le (b 1) hk) hm, refComb_one]
    have key := eq_of_divisorSum_eq b (refComb (b 1))
      (fun m hm => by rw [hB m hm, hB' m hm]) n (by omega)
    rw [key, refComb_of_two_le (b 1) hn]
  · intro h p n hp hn
    have hpn : 1 ≤ p * n :=
      Nat.one_le_iff_ne_zero.mpr (Nat.mul_ne_zero hp.ne_zero (by omega))
    rw [divisorSum_eq_add_log_of_eq_vonMangoldt b h hpn,
      divisorSum_eq_add_log_of_eq_vonMangoldt b h hn]
    have hlog : Real.log ((p * n : ℕ) : ℝ)
        = Real.log (p : ℝ) + Real.log (n : ℝ) := by
      push_cast
      exact Real.log_mul (Nat.cast_ne_zero.mpr hp.ne_zero)
        (Nat.cast_ne_zero.mpr (by omega))
    rw [hlog]
    ring

/-! ### The axiom audit.

    All four proved targets should report exactly the three foundational
    Mathlib axioms `[propext, Classical.choice, Quot.sound]`: no `sorryAx`,
    no zero data, no RH input. The verbatim output is recorded in the
    VERIFIER report. -/

#print axioms flat_ray_of_quasiInvariance
#print axioms flat_ray_of_prime_quasiInvariance
#print axioms divisorSum_le_divisorSum_mul_of_nonneg
#print axioms increments_eq_log_iff_eq_vonMangoldt

/-! ### V4: the arithmetic core of the G_log dense-translate rigidity lemma.

    Statement of the full V4 (`docs/03_research/b1_glog_rigidity.md`): a
    positive Radon measure `ν` on ℝ with `ν (A + log p) = p^(-β) * ν A` for
    every prime `p` and Borel `A` is `c * exp (-β x) dx`. Proof shape: twist
    by `exp (β x)` to make the cocycle an invariance, use density of the
    subgroup generated by `{log p}` (two primes suffice, via `log 2 / log 3`
    irrational from unique factorization), upgrade dense invariance to full
    invariance by vague continuity, and finish by Haar uniqueness on ℝ.

    THIS PASS proves the ARITHMETIC CORE that B1 calls "the work": the
    additive subgroup of ℝ generated by `{log p : p prime}` is DENSE. This
    is the single step that needs the prime structure (two primes suffice);
    everything downstream of it is generic measure theory on `(ℝ, +)`. We
    prove the sharp form (`log 2`, `log 3` already generate a dense
    subgroup), which is what the "two primes suffice" claim of B1 asserts.

    The remaining (measure-theoretic) assembly is documented as the V4-measure
    gap at the end of this section: it is generic and prime-free, and the one
    nontrivial analytic step (dense-translation-invariance upgrades to full
    translation-invariance by vague/`C_c` continuity) has no single packaged
    Mathlib lemma. -/

/-- `2 ^ n = 3 ^ m` in ℕ forces `n = 0` and `m = 0`: if `n ≥ 1` then `2`
    divides `3 ^ m`, impossible since `Nat.Coprime 2 (3 ^ m)`. The arithmetic
    seed of the irrationality of `log 2 / log 3`. -/
theorem two_pow_eq_three_pow {n m : ℕ} (h : 2 ^ n = 3 ^ m) : n = 0 ∧ m = 0 := by
  have hn : n = 0 := by
    by_contra hn0
    have h2 : (2 : ℕ) ∣ 3 ^ m := by
      rw [← h]; exact dvd_pow_self 2 hn0
    have hcop : Nat.Coprime 2 (3 ^ m) :=
      (Nat.Coprime.pow_right m (by decide : Nat.Coprime 2 3))
    have : (2 : ℕ) = 1 := Nat.eq_one_of_dvd_coprimes hcop (dvd_refl 2) h2
    exact absurd this (by norm_num)
  refine ⟨hn, ?_⟩
  subst hn
  simp only [pow_zero] at h
  -- 1 = 3 ^ m forces m = 0
  rcases Nat.eq_zero_or_pos m with hm | hm
  · exact hm
  · exfalso; have : (3 : ℕ) ∣ 1 := h ▸ dvd_pow_self 3 (by omega)
    omega

/-- `log 2` and `log 3` are rationally independent: `j • log 2 = k • log 3`
    with integers `j, k` forces `j = 0 ∧ k = 0`. (Equivalently `log 2 / log 3`
    is irrational.) This is what rules out cyclicity of the prime-log
    subgroup. -/
theorem zsmul_log_two_eq_zsmul_log_three {j k : ℤ}
    (h : (j : ℝ) * Real.log 2 = (k : ℝ) * Real.log 3) : j = 0 ∧ k = 0 := by
  -- `j log 2 = k log 3` means `log (2^j) = log (3^k)` (as rpow), so `2^j = 3^k`
  -- as positive reals; clearing to ℕ powers via sign analysis gives the seed.
  have h2pos : (0 : ℝ) < 2 := by norm_num
  have h3pos : (0 : ℝ) < 3 := by norm_num
  have hlog2 : 0 < Real.log 2 := Real.log_pos (by norm_num)
  have hlog3 : 0 < Real.log 3 := Real.log_pos (by norm_num)
  -- exponentiate: (2:ℝ)^(j:ℝ) = (3:ℝ)^(k:ℝ) using log injectivity on positives
  have hrpow : (2 : ℝ) ^ (j : ℝ) = (3 : ℝ) ^ (k : ℝ) := by
    have e2 : Real.log ((2 : ℝ) ^ (j : ℝ)) = (j : ℝ) * Real.log 2 :=
      Real.log_rpow h2pos _
    have e3 : Real.log ((3 : ℝ) ^ (k : ℝ)) = (k : ℝ) * Real.log 3 :=
      Real.log_rpow h3pos _
    have hpos2 : (0 : ℝ) < (2 : ℝ) ^ (j : ℝ) := Real.rpow_pos_of_pos h2pos _
    have hpos3 : (0 : ℝ) < (3 : ℝ) ^ (k : ℝ) := Real.rpow_pos_of_pos h3pos _
    have : Real.log ((2 : ℝ) ^ (j : ℝ)) = Real.log ((3 : ℝ) ^ (k : ℝ)) := by
      rw [e2, e3, h]
    exact Real.log_injOn_pos (Set.mem_Ioi.mpr hpos2) (Set.mem_Ioi.mpr hpos3) this
  -- both exponents have the same sign because the base > 1 on each side forces
  -- j ≥ 0 ↔ LHS ≥ 1 ↔ RHS ≥ 1 ↔ k ≥ 0. Reduce to a common nonneg case.
  rcases le_or_gt 0 j with hj | hj
  · rcases le_or_gt 0 k with hk | hk
    · -- both nonneg: convert rpow with nat exponents to nat powers
      lift j to ℕ using hj with a ha
      lift k to ℕ using hk with b hb
      have hnat : (2 : ℝ) ^ a = (3 : ℝ) ^ b := by
        rw [← Real.rpow_natCast (2 : ℝ) a, ← Real.rpow_natCast (3 : ℝ) b]
        push_cast at hrpow ⊢; exact hrpow
      have hNat : (2 : ℕ) ^ a = (3 : ℕ) ^ b := by
        have := hnat
        rw [show (2 : ℝ) = ((2 : ℕ) : ℝ) by norm_num,
            show (3 : ℝ) = ((3 : ℕ) : ℝ) by norm_num] at this
        push_cast at this
        exact_mod_cast this
      obtain ⟨ha0, hb0⟩ := two_pow_eq_three_pow hNat
      subst ha0; subst hb0; simp
    · -- j ≥ 0, k < 0: LHS ≥ 1, RHS < 1, contradiction
      exfalso
      have hL : (1 : ℝ) ≤ (2 : ℝ) ^ (j : ℝ) :=
        Real.one_le_rpow (by norm_num) (by exact_mod_cast hj)
      have hR : (3 : ℝ) ^ (k : ℝ) < 1 :=
        Real.rpow_lt_one_of_one_lt_of_neg (by norm_num) (by exact_mod_cast hk)
      rw [hrpow] at hL; linarith
  · rcases le_or_gt 0 k with hk | hk
    · -- j < 0, k ≥ 0: LHS < 1, RHS ≥ 1, contradiction
      exfalso
      have hL : (2 : ℝ) ^ (j : ℝ) < 1 :=
        Real.rpow_lt_one_of_one_lt_of_neg (by norm_num) (by exact_mod_cast hj)
      have hR : (1 : ℝ) ≤ (3 : ℝ) ^ (k : ℝ) :=
        Real.one_le_rpow (by norm_num) (by exact_mod_cast hk)
      rw [hrpow] at hL; linarith
    · -- both negative: negate to the nonneg case via 2^(-j) = 3^(-k)
      have hrpow' : (2 : ℝ) ^ ((-j : ℤ) : ℝ) = (3 : ℝ) ^ ((-k : ℤ) : ℝ) := by
        rw [Int.cast_neg, Int.cast_neg, Real.rpow_neg (le_of_lt h2pos),
            Real.rpow_neg (le_of_lt h3pos), hrpow]
      lift (-j) to ℕ using (by omega : (0 : ℤ) ≤ -j) with a ha
      lift (-k) to ℕ using (by omega : (0 : ℤ) ≤ -k) with b hb
      have hNat : (2 : ℕ) ^ a = (3 : ℕ) ^ b := by
        have hnat : (2 : ℝ) ^ a = (3 : ℝ) ^ b := by
          rw [← Real.rpow_natCast (2 : ℝ) a, ← Real.rpow_natCast (3 : ℝ) b]
          push_cast at hrpow' ⊢; exact hrpow'
        rw [show (2 : ℝ) = ((2 : ℕ) : ℝ) by norm_num,
            show (3 : ℝ) = ((3 : ℕ) : ℝ) by norm_num] at hnat
        push_cast at hnat; exact_mod_cast hnat
      obtain ⟨ha0, hb0⟩ := two_pow_eq_three_pow hNat
      omega

/-- **V4 arithmetic core.** The additive subgroup of ℝ generated by
    `{log 2, log 3}` is DENSE. This is the single prime-dependent step of the
    B1 G_log rigidity lemma ("two primes suffice"): by `AddSubgroup.dense_or_cyclic`
    the subgroup is either dense or cyclic, and cyclicity is ruled out because
    `log 2` and `log 3` would then be integer multiples of a common generator,
    forcing `log 2 / log 3 ∈ ℚ`, contradicted by
    `zsmul_log_two_eq_zsmul_log_three`. Everything downstream in B1 is generic
    measure theory on `(ℝ, +)`; this lemma is where the arithmetic lives. -/
theorem dense_primeLogSubgroup :
    Dense ((AddSubgroup.closure {Real.log 2, Real.log 3} : AddSubgroup ℝ) : Set ℝ) := by
  rcases (AddSubgroup.closure {Real.log 2, Real.log 3}).dense_or_cyclic with hdense | hcyc
  · exact hdense
  · exfalso
    obtain ⟨a, ha⟩ := hcyc
    -- both generators lie in the cyclic group `closure {a}`
    have hmem2 : Real.log 2 ∈ AddSubgroup.closure {Real.log 2, Real.log 3} :=
      AddSubgroup.subset_closure (by left; rfl)
    have hmem3 : Real.log 3 ∈ AddSubgroup.closure {Real.log 2, Real.log 3} :=
      AddSubgroup.subset_closure (by right; rfl)
    rw [ha, AddSubgroup.mem_closure_singleton] at hmem2 hmem3
    obtain ⟨p, hp⟩ := hmem2
    obtain ⟨q, hq⟩ := hmem3
    -- log 2 = p • a, log 3 = q • a, so q • log 2 = (p q) • a = p • log 3
    have hcross : (q : ℝ) * Real.log 2 = (p : ℝ) * Real.log 3 := by
      have e2 : (p : ℝ) • a = Real.log 2 := by simpa [zsmul_eq_mul] using hp
      have e3 : (q : ℝ) • a = Real.log 3 := by simpa [zsmul_eq_mul] using hq
      rw [zsmul_eq_mul] at hp hq
      rw [← hp, ← hq]; ring
    obtain ⟨hq0, hp0⟩ := zsmul_log_two_eq_zsmul_log_three hcross
    -- then log 2 = 0 • a = 0, contradiction
    have : Real.log 2 = 0 := by rw [zsmul_eq_mul] at hp; rw [← hp, hp0]; simp
    exact absurd this (ne_of_gt (Real.log_pos (by norm_num)))

#print axioms dense_primeLogSubgroup

/-! ### V4-measure gap (documented, not proven here).

    With `dense_primeLogSubgroup` in hand, the remaining B1 assembly is
    generic measure theory on `(ℝ, +)` (no further prime input):

      1. twist `ν` by `exp (β x)` (`MeasureTheory.Measure.withDensity`) so
         the cocycle `ν (A + log p) = p^(-β) ν A` becomes plain translation
         invariance under each `log p`;
      2. the twisted measure is invariant under the dense subgroup
         `closure {log 2, log 3}` (proven dense just above);
      3. UPGRADE dense invariance to full translation invariance: this is the
         one analytic step with no single packaged Mathlib lemma. It is a
         Riesz/`C_c`-density argument: `∫ f (x + t) dμ` is continuous in `t`
         for `f ∈ C_c(ℝ)` (uniform continuity on the compact support), equals
         `∫ f dμ` on the dense set of `t`, hence everywhere; then `μ` is
         left-invariant by testing against `C_c`;
      4. finish by Haar uniqueness `MeasureTheory.Measure.isAddLeftInvariant_eq_smul`
         with `Real.isAddHaarMeasure_volume`, giving `μ = c • volume`, i.e.
         `ν = c • exp(-β x) dx`.

    Step 3 is the documented gap: Mathlib has `Continuous.integral` /
    `MeasureTheory.continuous_integral_comp_add` style continuity facts and
    `MeasureTheory.Measure.ext_of_forall_integral_eq`-type uniqueness, but
    not a one-shot "dense translation invariance implies full translation
    invariance for a Radon measure" lemma; assembling it is a medium measure
    development. Prime-free, hence outside the V4 arithmetic core proven here.
    Status: V4 arithmetic core PROVED; V4 measure assembly OPEN (no sorry in
    this file, the gap is a missing theorem stated above, not a stub). -/

/-! ### EF-positivity skeleton: the slope-1 lemma and flat-comb exclusion.

    These are the two unconditional lemmas the ADVERSARY report
    (`lcc_bc_transport.md` blocks 2-3) extracted. Both are statements ABOUT
    the explicit-formula pairing `EF(g) = arch(g) + pole(g) - comb(g)`. The
    analytic identity (EF) itself and the Fourier-side facts (the pole atom of
    a translate bump, nonneg-Fejer concentration at `r = 0`) are NOT in
    Mathlib (they live in `ExplicitFormula.lean` as the documented `#EF-*`
    targets). So we translate the COMBINATORIAL/SIGN core that those analytic
    facts feed into, taking the analytic inputs as explicit hypotheses. This
    is the "FiniteCertificates style": the theorem is the sign deduction, the
    analytic facts are its named premises. K1-clean: no zero location is used;
    the only zeta-specific real number is the archimedean trough value
    `Ω(0)` and `ζ(1/2)`, both source-side continuation data. -/

/-- **Slope-1 lemma (sign core).** ADVERSARY block 2. The windowed comb mass
    paired against a translate bump equals the pole atom up to a bounded
    remainder, so as the window translates to `+∞` the comb mass is pinned to
    the pole atom: slope exactly the residue 1.

    Translation to Lean: abstract the (EF) windowed identity as the hypothesis
    `hEF : combMass T = poleAtom T - remainder T` together with the analytic
    inputs `hpole : poleAtom T = A * Real.cosh (T / 2)` (the exact pole atom,
    `A > 0` the residue-normalised constant) and `hrem : |remainder T| ≤ C`
    (uniform boundedness of the archimedean-plus-tempered remainder). The
    conclusion is the two-sided pinch `|combMass T - A * Real.cosh (T/2)| ≤ C`,
    i.e. the windowed comb mass is `A cosh(T/2) + O(1)`: smoothed Chebyshev
    pinning with slope exactly the residue. No zeros, no measure theory: the
    content is that the pole organ sets the leading asymptotic and the rest is
    uniformly bounded. -/
theorem slope_one_pin (combMass poleAtom remainder : ℝ → ℝ) (A C : ℝ)
    (hEF : ∀ T : ℝ, combMass T = poleAtom T - remainder T)
    (hpole : ∀ T : ℝ, poleAtom T = A * Real.cosh (T / 2))
    (hrem : ∀ T : ℝ, |remainder T| ≤ C) :
    ∀ T : ℝ, |combMass T - A * Real.cosh (T / 2)| ≤ C := by
  intro T
  have h : combMass T - A * Real.cosh (T / 2) = -(remainder T) := by
    rw [hEF T, hpole T]; ring
  rw [h, abs_neg]
  exact hrem T

/-- The leading pole atom diverges: with `A > 0` the windowed comb mass grows
    without bound (slope cannot be `0` or negative). The quantitative form of
    "slope exactly 1": for any threshold `M`, far enough out the comb mass
    exceeds `M`. Pure consequence of `Real.cosh` being unbounded above. -/
theorem slope_one_diverges (combMass poleAtom remainder : ℝ → ℝ) (A C : ℝ)
    (hA : 0 < A)
    (hEF : ∀ T : ℝ, combMass T = poleAtom T - remainder T)
    (hpole : ∀ T : ℝ, poleAtom T = A * Real.cosh (T / 2))
    (hrem : ∀ T : ℝ, |remainder T| ≤ C) :
    ∀ M : ℝ, ∃ T : ℝ, M < combMass T := by
  intro M
  -- combMass T ≥ A cosh(T/2) - C. Bound cosh y ≥ (y+1)/2 (drop exp(-y) ≥ 0,
  -- then exp y ≥ y+1), which is unbounded; pick T large.
  have hpin := slope_one_pin combMass poleAtom remainder A C hEF hpole hrem
  -- the target value the comb must clear at r-window T/2 = y
  set K : ℝ := (M + C) / A + 1 with hKdef
  set T : ℝ := 2 * (2 * K) with hTdef
  refine ⟨T, ?_⟩
  have hhalf : T / 2 = 2 * K := by rw [hTdef]; ring
  have hcosh : K ≤ Real.cosh (T / 2) := by
    rw [hhalf]
    have hge : Real.exp (2 * K) / 2 ≤ Real.cosh (2 * K) := by
      rw [Real.cosh_eq]
      have : 0 ≤ Real.exp (-(2 * K)) := le_of_lt (Real.exp_pos _)
      linarith
    have hexp : 2 * K + 1 ≤ Real.exp (2 * K) := by
      have := Real.add_one_le_exp (2 * K); linarith
    -- exp(2K)/2 ≥ (2K+1)/2 ≥ K
    have : (2 * K + 1) / 2 ≤ Real.exp (2 * K) / 2 := by linarith
    have hKle : K ≤ (2 * K + 1) / 2 := by linarith
    linarith
  have hmul : A * K ≤ A * Real.cosh (T / 2) := mul_le_mul_of_nonneg_left hcosh (le_of_lt hA)
  have hcancel : A * K = M + C + A := by
    rw [hKdef, mul_add, mul_one, mul_div_cancel₀ _ (ne_of_gt hA)]
  rw [hcancel] at hmul
  have h2 := abs_le.mp (hpin T)
  -- combMass T ≥ A cosh(T/2) - C ≥ (M + C + A) - C = M + A > M
  linarith [h2.1]

/-- **Flat-comb exclusion (sign core).** ADVERSARY block 3, case `c₁ = 1`.
    The first FiniteCertificates-style EF-positivity theorem. With the pole
    atom cancelled (the scale pinned to `c₁ = 1` by the pole), the flat ray
    induces a spectral density whose value at `r = 0` is the NEGATIVE number
    `Ω(0) - 2 Re ζ(1/2)`. A nonneg-Fejer test concentrating at `r = 0` then
    pairs the comb to a strictly negative value, contradicting cone
    positivity. Hence the flat comb is NOT a member of the zeta crystal cone.

    Translation to Lean: the analytic facts are the hypotheses
      `hdens : density0 = Ω0 - 2 * ζhalf`            (the induced density at 0),
      `htrough : Ω0 < 2 * ζhalf`                     (the archimedean trough
                                                       beats the flat comb's
                                                       supply: `Ω(0) ≈ -5.372`,
                                                       `2 ζ(1/2) ≈ -2.921`),
      `hpair : ∀ test, fejerNonneg test → pairing test = weight test * density0`
                                                     (concentration: a nonneg
                                                      Fejer test reads off the
                                                      density at 0),
      `hweight : 0 < weight testStar` and `fejerNonneg testStar`.
    The conclusion is `pairing testStar < 0`, i.e. EF-positivity is VIOLATED,
    so the flat comb is excluded. The proof is the sign multiplication
    `positive weight × negative density < 0`. K1-clean: `Ω0` and `ζhalf` are
    source-side; no zero location enters. -/
theorem flat_comb_excluded {density0 Ω0 ζhalf : ℝ}
    {weight pairing : (ℝ → ℝ) → ℝ} {fejerNonneg : (ℝ → ℝ) → Prop} {testStar : ℝ → ℝ}
    (hdens : density0 = Ω0 - 2 * ζhalf)
    (htrough : Ω0 < 2 * ζhalf)
    (hpair : ∀ test, fejerNonneg test → pairing test = weight test * density0)
    (hweight : 0 < weight testStar) (hfej : fejerNonneg testStar) :
    pairing testStar < 0 := by
  have hd : density0 < 0 := by rw [hdens]; linarith
  rw [hpair testStar hfej]
  exact mul_neg_of_pos_of_neg hweight hd

/-- Concrete instantiation of the trough hypothesis with the dossier's
    numerical values: `Ω(0) ≈ -5.3721834 < 2 ζ(1/2) ≈ -2.9207090`. The
    induced density at `r = 0` is `≈ -2.4514744 < 0`. Both constants are
    source-side continuation data (K1-clean); the inequality is decidable
    rational arithmetic, certifying the trough premise of `flat_comb_excluded`
    is not vacuous. -/
theorem flat_comb_trough_witness :
    (-5.3721834 : ℝ) < 2 * (-1.4603545 : ℝ) ∧
      (-5.3721834 : ℝ) - 2 * (-1.4603545 : ℝ) < 0 := by
  constructor <;> norm_num

#print axioms slope_one_pin
#print axioms slope_one_diverges
#print axioms flat_comb_excluded
#print axioms flat_comb_trough_witness

end ZetaRH.CrystalCocycle
