/-
The NG1 kernel of the model-theoretic Frobenius arc (LEARNINGS #156): the
endomorphism-rigidity of imported arithmetic, machine-checked.

Dossier: docs/03_research/model_theoretic_frobenius.md (Section 3, "NG1: the Fermat
degeneracy is limit-independent rigidity"). The one-line theorem is the point: every
unital ring endomorphism of every unital receptacle fixes the arithmetic the
receptacle imports (the prime ring, and Q wherever Q is present), so no
endomorphism-shaped filler of the R1 slot can move arithmetic, on any receptacle,
limit-built or not. Fermat's little theorem is the coordinatewise witness for the
ultraproduct Frobenius sigma on K = prod_p conj(F_p) / U: at every prime the local
Frobenius is already the identity on the prime field, which is why the diagonal
arithmetic survives the ultralimit inside Fix(sigma).

Target T1 (#MTF-1), four faces, all sorry-free. Each proof is a near-one-liner over
Mathlib; the value is pinning the project-facing statements, not the proof effort
(dossier Section 11, "T1 ... the value is pinning the statement").

  (a) the prime ring is fixed: any ring endomorphism fixes every natural and integer
      cast (`endo_fixes_natCast`, `endo_fixes_intCast`);
  (b) the division-ring form: every endomorphism of a division ring fixes every
      rational cast (`endo_fixes_ratCast`);
  (c) the Fermat coordinatewise witness: `x^p = x` on `ZMod p`
      (`fermat_little_zmod`), so the local Frobenius IS the identity on the prime
      field at every p (`frobenius_zmod_eq_id`), and the prime field is
      endomorphism-rigid outright (`zmod_endo_eq_id`);
  (d) the NG1 composite: every ring endomorphism of every Q-algebra fixes the
      canonically imported Q pointwise, `sigma . algebraMap Q R = algebraMap Q R`
      (`ng1_rigidity`), covering the non-field receptacles of dossier Section 3
      (adeles, Z/p^2 ultraproducts, Witt ultraproducts) in one statement.

The cardinality half of NG1 (the forced fixed set has cardinality at least continuum)
is target T4 (#MTF-4) and is deliberately NOT attempted here; T2 (the ultraproduct
object itself) and T3 (the Borger trivialization statement) are also separate.
-/

import Mathlib.Data.Rat.Cast.Defs
import Mathlib.Data.ZMod.Basic
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.Algebra.Algebra.Defs

namespace ZetaRH.ModelTheoreticFrobenius

/-! ## #MTF-1a: every unital ring endomorphism fixes the prime ring

    NG1's base clause (dossier Section 3, "fixes the prime ring Z.1 pointwise"):
    `f 1 = 1` forces `f` to fix every element the ring imports from N and Z. This is
    Mathlib's `map_natCast` / `map_intCast`, restated as the project-facing lemma the
    target table points at. -/

/-- **The prime semiring is fixed.** Every unital ring endomorphism of every
    (non-associative) semiring fixes every natural-number cast: `f (n : R) = n`.
    The seed of NG1: imported arithmetic cannot be moved by ring endomorphisms. -/
theorem endo_fixes_natCast {R : Type*} [NonAssocSemiring R] (f : R →+* R) (n : ℕ) :
    f (n : R) = (n : R) :=
  map_natCast f n

/-- **The prime ring is fixed.** Every unital ring endomorphism of every
    (non-associative) ring fixes every integer cast: `f (n : R) = n`. The #145
    statement "the only endomorphism of Z is the identity" as it persists in every
    receptacle: the copy of Z generated by 1 is pointwise rigid. -/
theorem endo_fixes_intCast {R : Type*} [NonAssocRing R] (f : R →+* R) (n : ℤ) :
    f (n : R) = (n : R) :=
  map_intCast f n

/-! ## #MTF-1b: the division-ring form

    On a division ring the prime field contains the rationals (units have unique
    inverses, so `f (n⁻¹) = n⁻¹`), and NG1 extends to every rational cast. Applied to
    `K = prod_p conj(F_p) / U` (characteristic 0, so the prime field is Q): the
    ultraproduct Frobenius, and every other endomorphism of K, is the identity on the
    diagonal copy of Q. -/

/-- **The prime field of a division ring is fixed.** Every unital ring endomorphism
    of every division ring fixes every rational cast: `f (q : K) = q`. For a
    characteristic-0 division ring the rational casts ARE the prime field, so this is
    NG1 on fields: the fixed set of any endomorphism-shaped Frobenius contains all of
    Q, hence is infinite (the S1 kill; the finite-field disanalogy is that there the
    prime field is finite and Frobenius-fixing it is harmless). -/
theorem endo_fixes_ratCast {K : Type*} [DivisionRing K] (f : K →+* K) (q : ℚ) :
    f (q : K) = (q : K) :=
  map_ratCast f q

/-! ## #MTF-1c: the Fermat coordinatewise witness

    Fermat's little theorem is exactly the statement that the local Frobenius
    `x ↦ x^p` is already the identity on the prime field `F_p = ZMod p` at every
    prime: the diagonal integers of the ultraproduct are Frobenius-fixed coordinate
    by coordinate, which is how the NG1 degeneracy arises in `K` before any general
    rigidity is invoked. -/

/-- **Fermat's little theorem on the prime field**: `x^p = x` for every `x : ZMod p`.
    The coordinatewise witness of NG1: at every prime p, the p-power map fixes every
    element of the prime field, so the diagonal arithmetic of the ultraproduct is
    Frobenius-fixed at (U-almost) every coordinate. -/
theorem fermat_little_zmod {p : ℕ} [Fact p.Prime] (x : ZMod p) : x ^ p = x :=
  ZMod.pow_card x

/-- **The local Frobenius is the identity on the prime field at every p**: the
    Frobenius ring endomorphism of `ZMod p` equals `RingHom.id`. Fermat's little
    theorem packaged as the degeneracy statement: the one structure map the
    characteristic-p world contributes to the ultralimit acts trivially on exactly
    the subfield where the global arithmetic lands. -/
theorem frobenius_zmod_eq_id (p : ℕ) [Fact p.Prime] :
    frobenius (ZMod p) p = RingHom.id (ZMod p) :=
  ZMod.frobenius_zmod p

/-- **The prime field at p is endomorphism-rigid outright**: every unital ring
    endomorphism of `ZMod n` is the identity (it is determined on the image of `1`,
    which is everything). The characteristic-p mirror of `endo_fixes_intCast`:
    prime-field rigidity holds at every coordinate, not just for the Frobenius. -/
theorem zmod_endo_eq_id (n : ℕ) (f : ZMod n →+* ZMod n) : f = RingHom.id (ZMod n) :=
  RingHom.ext_zmod f _

/-! ## #MTF-1d: the NG1 composite

    The receptacle-general form (dossier Section 3, adversary-corrected scope): every
    ring endomorphism of every Q-algebra fixes the canonically imported Q pointwise.
    `algebraMap Q R` is the unique ring homomorphism Q →+* R (Mathlib:
    `RingHom.ext_rat`), so composing with any endomorphism cannot move it. This
    covers, verbatim, every receptacle named in the dossier: fields of characteristic
    0, the adele ring, `prod_p Z/p^2 / U`, and Witt-vector ultraproducts, all
    Q-algebras. The kill is limit-independent: no ultrafilter appears anywhere in the
    statement or the proof. -/

/-- **NG1 (the composite rigidity).** Every unital ring endomorphism `σ` of every
    Q-algebra `R` fixes the canonically imported Q: `σ ∘ algebraMap ℚ R = algebraMap
    ℚ R`. Since ring homomorphisms out of ℚ are unique (`RingHom.ext_rat`), the
    composite is forced back to the algebra map. Consequence for the R1 slot: an
    endomorphism-shaped Frobenius on any ring-shaped receptacle has fixed set
    containing all of the imported ℚ, so its fixed arithmetic is neither isolated nor
    prime-indexed. The filler must move arithmetic by non-endomorphism means. -/
theorem ng1_rigidity {R : Type*} [Semiring R] [Algebra ℚ R] (σ : R →+* R) :
    σ.comp (algebraMap ℚ R) = algebraMap ℚ R :=
  RingHom.ext_rat _ _

/-- **NG1, pointwise form**: `σ (algebraMap ℚ R q) = algebraMap ℚ R q` for every
    rational `q` and every ring endomorphism `σ` of the ℚ-algebra `R`. The form the
    dossier states as "the Frobenius never couples to the imported arithmetic". -/
theorem ng1_rigidity_apply {R : Type*} [Semiring R] [Algebra ℚ R] (σ : R →+* R)
    (q : ℚ) : σ (algebraMap ℚ R q) = algebraMap ℚ R q :=
  RingHom.congr_fun (ng1_rigidity σ) q

end ZetaRH.ModelTheoreticFrobenius
