/-
The VERIFIER target-discharge queue: typed statement drafts for the dossier
targets that are typable against Mathlib TODAY.

Registry: `experiments/lemma_db/lean_targets.json` (regenerated by
`experiments/lemma_db/lean_targets.py`); human-readable queue with the triage
verdicts: `experiments/lemma_db/verifier_queue.md`.

STATUS: DRAFT-UNCHECKED / UNVERIFIED-on-this-box. This file was authored on a
machine WITHOUT the Lean toolchain (`lean/.lake` absent), so it has NOT been
elaborated. The statements deliberately use only API certain to exist at the
repo pin (Lean/Mathlib v4.30.0, all imports below already used by green
in-repo modules): `Real.log`, `Real.sqrt`, `Real.cosh`, `Polynomial.eval`,
`Polynomial.natDegree`, `Matrix` with `!![..]` notation, `Finset` sums. Every
body is `sorry` BY DESIGN (statement drafts in the house `ExplicitFormula`
style; the sorries carry queue IDs). This module is deliberately NOT imported
by `ZetaRH.lean`: wiring it into the build is the one-line edit
`import ZetaRH.VerifierQueue` there, to be done in a session with a working
toolchain once `lake build` confirms elaboration.

  #VQ-1a  (registry e1z-2 = e1v-2, the Lagrange/Cauchy-Schwarz kernel of the
          Christoffel interpolation identity `1/lambda_M(0) = sum_j
          l_j(0)^2 / w_j`, LEARNINGS #172/#175, e1z_v2_sharp.md target 2).
          Product form, so no division by the sum is needed: if the
          interpolation constraint `sum_j c_j p_j = 1` holds (over an M-atom
          set the Lagrange coefficients `c_j = l_j(0)` satisfy it for every
          polynomial of degree < M with `P(0) = 1`), then
          `1 <= (sum_j c_j^2 / w_j) * (sum_j w_j p_j^2)`. The polynomial-side
          Lagrange step is carried as the hypothesis `hpair`, in the honest
          KERNEL style of `#S4C-2` (which carried Chebyshev's bound the same
          way). Proof route for VERIFIER: expand
          `0 <= sum_j w_j (p_j - t c_j / w_j)^2` at `t = 1/B`, or apply the
          finite Cauchy-Schwarz `Finset.sum_mul_sq_le_sq_mul_sq` to
          `(c_j / sqrt w_j) * (sqrt w_j * p_j)`.

  #VQ-1b  the attainment half: the bound of #VQ-1a is an equality for the
          explicit minimizer `p_j = (c_j / w_j) / (sum_k c_k^2 / w_k)`, so
          `1/lambda_M(0)` really IS `sum_j c_j^2 / w_j`.

  #VQ-2   (registry e1v-1, Theorem V2 of LEARNINGS #172, discharging e1u
          VERIFIER target 6): the Chebyshev germ bound
          `lambda_M(0) <= cosh(2nG)^{-2}`, `n = floor((M-1)/2)`, stated as the
          EXISTENCE of the competitor polynomial: atoms in the two-sided band
          `g <= |x_j| <= T`, probability weights, and a polynomial of degree
          `<= M-1` with `P(0) = 1` whose weighted square sum is at most
          `cosh(2nG)^{-2}`. The competitor is `T_n` composed with the
          quadratic band map, normalized at 0; Mathlib has the Chebyshev
          polynomials (`Polynomial.Chebyshev.T`). `G` is the Green's function
          of the band complement at 0 in closed form. Mathlib gap recorded:
          there is no `Real.arcosh`, so `arcoshReal` below is the standard
          `log (x + sqrt (x^2 - 1))` form (itself a small upstream candidate).

  #VQ-3a / #VQ-3b (registry e1u-2): the nilpotent transfer atoms of the
          canonical-chain gauge. `J u u^T` squares to zero (indivisible
          intervals have polynomial transfer of exactly degree one), and the
          degree-one propagators compose additively in the length coordinate.
          Two-line matrix lemmas once elaborated; stated on explicit `!![..]`
          matrices to avoid any API risk.
-/

import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Sqrt
import Mathlib.Analysis.Complex.Exponential
import Mathlib.Algebra.Polynomial.Derivative
import Mathlib.LinearAlgebra.Matrix.Notation

namespace ZetaRH.VerifierQueue

/-! ## #VQ-1: the Lagrange/Cauchy-Schwarz kernel of the Christoffel identity -/

/-- **#VQ-1a (e1z-2 / e1v-2 kernel).** With positive weights `w` and the
    interpolation constraint `∑ j, c j * p j = 1` (the full-degree Lagrange
    identity `P(0) = ∑ j, ℓ_j(0) P(x_j)`, carried as a hypothesis), the paired
    Cauchy-Schwarz lower bound holds in product form:
    `1 ≤ (∑ j, c j ^ 2 / w j) * (∑ j, w j * p j ^ 2)`. Specializing `c` to the
    Lagrange values `ℓ_j(0)` gives the inequality half of the Christoffel
    interpolation identity `1/λ_M(0) = ∑ j, ℓ_j(0)^2 / w j`. -/
theorem christoffel_pairing_lower_bound {M : ℕ} (w c p : Fin M → ℝ)
    (hw : ∀ j, 0 < w j) (hpair : ∑ j, c j * p j = 1) :
    1 ≤ (∑ j, c j ^ 2 / w j) * ∑ j, w j * p j ^ 2 := by
  sorry -- #VQ-1a

/-- **#VQ-1b (e1z-2 / e1v-2 kernel, attainment).** The #VQ-1a bound is sharp:
    some admissible `p` (the explicit minimizer `p j = (c j / w j) / B` with
    `B = ∑ k, c k ^ 2 / w k`) satisfies the constraint and attains equality,
    so the Christoffel minimum at full degree equals `(∑ j, c j ^ 2 / w j)⁻¹`
    exactly. -/
theorem christoffel_pairing_attained {M : ℕ} (w c : Fin M → ℝ)
    (hw : ∀ j, 0 < w j) (hc : ∃ j, c j ≠ 0) :
    ∃ p : Fin M → ℝ,
      (∑ j, c j * p j = 1) ∧
      (∑ j, c j ^ 2 / w j) * ∑ j, w j * p j ^ 2 = 1 := by
  sorry -- #VQ-1b

/-! ## #VQ-2: Theorem V2, the Chebyshev germ bound (e1v-1) -/

/-- Inverse hyperbolic cosine in the standard logarithmic closed form.
    Mathlib has `Real.arsinh` but (as of the v4.30.0 pin) no `Real.arcosh`;
    this local definition records that gap and is itself a small upstream
    candidate. For `1 ≤ x` it satisfies `Real.cosh (arcoshReal x) = x`. -/
noncomputable def arcoshReal (x : ℝ) : ℝ :=
  Real.log (x + Real.sqrt (x ^ 2 - 1))

/-- The Green's function at `0` of the complement of the two-sided band
    `E = [-T, -g] ∪ [g, T]`, in closed form:
    `G = (1/2) * arcosh ((T^2 + g^2) / (T^2 - g^2))` (e1v/#172, e1z). -/
noncomputable def bandGreen (g T : ℝ) : ℝ :=
  arcoshReal ((T ^ 2 + g ^ 2) / (T ^ 2 - g ^ 2)) / 2

/-- **#VQ-2 (e1v-1): Theorem V2 of LEARNINGS #172.** For atoms `x j` in the
    two-sided band `g ≤ |x j| ≤ T` (`0 < g < T`) and probability weights `w`,
    there is a polynomial of degree at most `M - 1`, normalized to `1` at `0`,
    whose weighted square sum over the atoms is at most `cosh (2 n G)⁻¹ ^ 2`
    with `n = (M - 1) / 2` (Nat division = the floor) and `G = bandGreen g T`.
    Consequently the Christoffel function satisfies
    `λ_M(0) ≤ cosh (2 n G)⁻¹ ^ 2`: the germ-length blowup with the explicit
    rate, the theorem that discharged e1u VERIFIER target 6. The competitor is
    the Chebyshev polynomial `T_n` composed with the quadratic map sending the
    band onto `[-1, 1]`, normalized at `0`; `Polynomial.Chebyshev.T` carries
    the Mathlib side. -/
theorem v2_germ_bound (M : ℕ) (g T : ℝ) (hg : 0 < g) (hgT : g < T)
    (x w : Fin M → ℝ) (hx : ∀ j, g ≤ |x j| ∧ |x j| ≤ T)
    (hw : ∀ j, 0 ≤ w j) (hw1 : ∑ j, w j = 1) :
    ∃ P : Polynomial ℝ, P.natDegree ≤ M - 1 ∧ P.eval 0 = 1 ∧
      ∑ j, w j * P.eval (x j) ^ 2 ≤
        (Real.cosh (2 * (((M - 1) / 2 : ℕ) : ℝ) * bandGreen g T))⁻¹ ^ 2 := by
  sorry -- #VQ-2

/-! ## #VQ-3: the nilpotent transfer atoms (e1u-2) -/

/-- The rank-one chain generator `J u uᵀ` of the Kac-Krein footprint
    construction, on explicit `2 × 2` matrices: `J = !![0, 1; -1, 0]` and
    `u uᵀ = !![u 0 * u 0, u 0 * u 1; u 1 * u 0, u 1 * u 1]`. -/
noncomputable def rankOneTransfer (u : Fin 2 → ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  !![(0 : ℝ), 1; -1, 0] * !![u 0 * u 0, u 0 * u 1; u 1 * u 0, u 1 * u 1]

/-- **#VQ-3a (e1u-2, nilpotency).** `(J u uᵀ) ^ 2 = 0`: the symplectic form
    vanishes on the diagonal (`uᵀ J u = 0`), so indivisible intervals have
    polynomial transfer of exactly degree one. One of the two matrix facts
    the whole e1u rung leans on. -/
theorem rankOneTransfer_sq (u : Fin 2 → ℝ) :
    rankOneTransfer u ^ 2 = 0 := by
  sorry -- #VQ-3a

/-- **#VQ-3b (e1u-2, exact propagator).** The degree-one propagators along an
    indivisible interval compose additively in the length coordinate:
    `(1 + z • J u uᵀ) * (1 + z' • J u uᵀ) = 1 + (z + z') • J u uᵀ`.
    Immediate from #VQ-3a once elaborated. -/
theorem rankOneTransfer_propagator (u : Fin 2 → ℝ) (z z' : ℝ) :
    (1 + z • rankOneTransfer u) * (1 + z' • rankOneTransfer u) =
      1 + (z + z') • rankOneTransfer u := by
  sorry -- #VQ-3b

end ZetaRH.VerifierQueue
