/-
The VERIFIER target-discharge queue: typed statement drafts for the dossier
targets that are typable against Mathlib TODAY.

Registry: `experiments/lemma_db/lean_targets.json` (regenerated by
`experiments/lemma_db/lean_targets.py`); human-readable queue with the triage
verdicts: `experiments/lemma_db/verifier_queue.md`.

STATUS: DISCHARGED on this box (Lean/Mathlib at the repo pin, v4.30.0). The
five queue targets below are proved sorry-free; the module is imported by
`ZetaRH.lean` and builds with the full library. Axiom footprint of every
theorem: exactly [propext, Classical.choice, Quot.sound]. The statements use
only pinned API: `Real.log`, `Real.sqrt`, `Real.cosh`, `Polynomial.eval`,
`Polynomial.natDegree`, `Polynomial.Chebyshev.T`, `Matrix` with `!![..]`
notation, `Finset` sums.

  #VQ-1a  (registry e1z-2 = e1v-2, the Lagrange/Cauchy-Schwarz kernel of the
          Christoffel interpolation identity `1/lambda_M(0) = sum_j
          l_j(0)^2 / w_j`, LEARNINGS #172/#175, e1z_v2_sharp.md target 2).
          Product form, so no division by the sum is needed: if the
          interpolation constraint `sum_j c_j p_j = 1` holds (over an M-atom
          set the Lagrange coefficients `c_j = l_j(0)` satisfy it for every
          polynomial of degree < M with `P(0) = 1`), then
          `1 <= (sum_j c_j^2 / w_j) * (sum_j w_j p_j^2)`. The polynomial-side
          Lagrange step is carried as the hypothesis `hpair`, in the honest
          KERNEL style of `#S4C-2` (which carried Chebyshev's bound the same
          way). Proved by the finite Cauchy-Schwarz
          `Finset.sum_mul_sq_le_sq_mul_sq` applied to
          `(c_j / sqrt w_j) * (sqrt w_j * p_j)`.

  #VQ-1b  the attainment half: the bound of #VQ-1a is an equality for the
          explicit minimizer `p_j = (c_j / w_j) / (sum_k c_k^2 / w_k)`, so
          `1/lambda_M(0)` really IS `sum_j c_j^2 / w_j`.

  #VQ-2   (registry e1v-1, Theorem V2 of LEARNINGS #172, discharging e1u
          VERIFIER target 6): the Chebyshev germ bound
          `lambda_M(0) <= cosh(2nG)^{-2}`, `n = floor((M-1)/2)`, stated as the
          EXISTENCE of the competitor polynomial: atoms in the two-sided band
          `g <= |x_j| <= T`, probability weights, and a polynomial of degree
          `<= M-1` with `P(0) = 1` whose weighted square sum is at most
          `cosh(2nG)^{-2}`. The competitor is `T_n` composed with the
          quadratic band map, normalized at 0; Mathlib carries the Chebyshev
          polynomials (`Polynomial.Chebyshev.T`) and their cosh
          characterization (`T_real_cosh`). `G` is the Green's function of
          the band complement at 0 in closed form. Mathlib gap recorded:
          there is no `Real.arcosh`, so `arcoshReal` below is the standard
          `log (x + sqrt (x^2 - 1))` form (itself a small upstream candidate).

  #VQ-3a / #VQ-3b (registry e1u-2): the nilpotent transfer atoms of the
          canonical-chain gauge. `J u u^T` squares to zero (indivisible
          intervals have polynomial transfer of exactly degree one), and the
          degree-one propagators compose additively in the length coordinate.
          Two-line matrix lemmas once elaborated; stated on explicit `!![..]`
          matrices to avoid any API risk.
-/

import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Sqrt
import Mathlib.Analysis.Complex.Exponential
import Mathlib.Algebra.Polynomial.Derivative
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.Algebra.Order.BigOperators.Ring.Finset
import Mathlib.Algebra.BigOperators.Field
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Chebyshev.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Inverse
import Mathlib.Analysis.SpecialFunctions.Trigonometric.DerivHyp
import Mathlib.Data.Real.Sqrt

namespace ZetaRH.VerifierQueue

/-! ## #VQ-1: the Lagrange/Cauchy-Schwarz kernel of the Christoffel identity -/

/-- **#VQ-1a (e1z-2 / e1v-2 kernel).** With positive weights `w` and the
    interpolation constraint `∑ j, c j * p j = 1` (the full-degree Lagrange
    identity `P(0) = ∑ j, ℓ_j(0) P(x_j)`, carried as a hypothesis), the paired
    Cauchy-Schwarz lower bound holds in product form:
    `1 ≤ (∑ j, c j ^ 2 / w j) * (∑ j, w j * p j ^ 2)`. Specializing `c` to the
    Lagrange values `ℓ_j(0)` gives the inequality half of the Christoffel
    interpolation identity `1/λ_M(0) = ∑ j, ℓ_j(0)^2 / w j`. -/
theorem christoffel_pairing_lower_bound {M : ℕ} (w c p : Fin M → ℝ)
    (hw : ∀ j, 0 < w j) (hpair : ∑ j, c j * p j = 1) :
    1 ≤ (∑ j, c j ^ 2 / w j) * ∑ j, w j * p j ^ 2 := by
  -- #VQ-1a: finite Cauchy-Schwarz applied to `(c j / √(w j)) * (√(w j) * p j)`.
  have e1 : (∑ j, c j / Real.sqrt (w j) * (Real.sqrt (w j) * p j)) = ∑ j, c j * p j := by
    refine Finset.sum_congr rfl fun j _ => ?_
    have hs : Real.sqrt (w j) ≠ 0 := (Real.sqrt_pos.mpr (hw j)).ne'
    have h : c j / Real.sqrt (w j) * (Real.sqrt (w j) * p j)
        = Real.sqrt (w j) / Real.sqrt (w j) * (c j * p j) := by ring
    rw [h, div_self hs, one_mul]
  have e2 : (∑ j, (c j / Real.sqrt (w j)) ^ 2) = ∑ j, c j ^ 2 / w j := by
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [div_pow, Real.sq_sqrt (hw j).le]
  have e3 : (∑ j, (Real.sqrt (w j) * p j) ^ 2) = ∑ j, w j * p j ^ 2 := by
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [mul_pow, Real.sq_sqrt (hw j).le]
  calc (1 : ℝ) = 1 ^ 2 := (one_pow 2).symm
    _ = (∑ j, c j * p j) ^ 2 := by rw [hpair]
    _ = (∑ j, c j / Real.sqrt (w j) * (Real.sqrt (w j) * p j)) ^ 2 := by rw [e1]
    _ ≤ (∑ j, (c j / Real.sqrt (w j)) ^ 2) * ∑ j, (Real.sqrt (w j) * p j) ^ 2 :=
        Finset.sum_mul_sq_le_sq_mul_sq Finset.univ _ _
    _ = (∑ j, c j ^ 2 / w j) * ∑ j, w j * p j ^ 2 := by rw [e2, e3]

/-- **#VQ-1b (e1z-2 / e1v-2 kernel, attainment).** The #VQ-1a bound is sharp:
    some admissible `p` (the explicit minimizer `p j = (c j / w j) / B` with
    `B = ∑ k, c k ^ 2 / w k`) satisfies the constraint and attains equality,
    so the Christoffel minimum at full degree equals `(∑ j, c j ^ 2 / w j)⁻¹`
    exactly. -/
theorem christoffel_pairing_attained {M : ℕ} (w c : Fin M → ℝ)
    (hw : ∀ j, 0 < w j) (hc : ∃ j, c j ≠ 0) :
    ∃ p : Fin M → ℝ,
      (∑ j, c j * p j = 1) ∧
      (∑ j, c j ^ 2 / w j) * ∑ j, w j * p j ^ 2 = 1 := by
  -- #VQ-1b: exhibit the explicit minimizer and evaluate both sums.
  obtain ⟨j0, hj0⟩ := hc
  set B : ℝ := ∑ k, c k ^ 2 / w k with hBdef
  have hBpos : 0 < B := by
    refine Finset.sum_pos' (fun i _ => ?_) ⟨j0, Finset.mem_univ _, ?_⟩
    · have hwi := hw i
      positivity
    · have hwj := hw j0
      positivity
  have hBne : B ≠ 0 := hBpos.ne'
  refine ⟨fun j => c j / w j / B, ?_, ?_⟩
  · have h1 : ∀ j : Fin M, c j * (c j / w j / B) = c j ^ 2 / w j / B := fun j => by ring
    rw [Finset.sum_congr rfl fun j _ => h1 j, ← Finset.sum_div, ← hBdef, div_self hBne]
  · have h2 : ∀ j : Fin M, w j * (c j / w j / B) ^ 2 = c j ^ 2 / w j / B ^ 2 := by
      intro j
      have hwj : w j ≠ 0 := (hw j).ne'
      field_simp
    rw [Finset.sum_congr rfl fun j _ => h2 j, ← Finset.sum_div, ← hBdef, pow_two,
      div_mul_eq_div_div, div_self hBne, mul_one_div, div_self hBne]

/-! ## #VQ-2: Theorem V2, the Chebyshev germ bound (e1v-1) -/

/-- Inverse hyperbolic cosine in the standard logarithmic closed form.
    Mathlib has `Real.arsinh` but (as of the v4.30.0 pin) no `Real.arcosh`;
    this local definition records that gap and is itself a small upstream
    candidate. For `1 ≤ x` it satisfies `Real.cosh (arcoshReal x) = x`. -/
noncomputable def arcoshReal (x : ℝ) : ℝ :=
  Real.log (x + Real.sqrt (x ^ 2 - 1))

/-- The defining property of `arcoshReal` on `1 ≤ x`. -/
theorem cosh_arcoshReal {x : ℝ} (hx : 1 ≤ x) : Real.cosh (arcoshReal x) = x := by
  have hsq : Real.sqrt (x ^ 2 - 1) ^ 2 = x ^ 2 - 1 := Real.sq_sqrt (by nlinarith)
  have hy : 0 < x + Real.sqrt (x ^ 2 - 1) :=
    lt_of_lt_of_le zero_lt_one (le_add_of_le_of_nonneg hx (Real.sqrt_nonneg _))
  have hinv : (x + Real.sqrt (x ^ 2 - 1))⁻¹ = x - Real.sqrt (x ^ 2 - 1) := by
    refine inv_eq_of_mul_eq_one_right ?_
    nlinarith [hsq]
  rw [arcoshReal, Real.cosh_eq, Real.exp_log hy, Real.exp_neg, Real.exp_log hy, hinv]
  ring

/-- The Green's function at `0` of the complement of the two-sided band
    `E = [-T, -g] ∪ [g, T]`, in closed form:
    `G = (1/2) * arcosh ((T^2 + g^2) / (T^2 - g^2))` (e1v/#172, e1z). -/
noncomputable def bandGreen (g T : ℝ) : ℝ :=
  arcoshReal ((T ^ 2 + g ^ 2) / (T ^ 2 - g ^ 2)) / 2

/-- **#VQ-2 (e1v-1): Theorem V2 of LEARNINGS #172.** For atoms `x j` in the
    two-sided band `g ≤ |x j| ≤ T` (`0 < g < T`) and probability weights `w`,
    there is a polynomial of degree at most `M - 1`, normalized to `1` at `0`,
    whose weighted square sum over the atoms is at most `cosh (2 n G)⁻¹ ^ 2`
    with `n = (M - 1) / 2` (Nat division = the floor) and `G = bandGreen g T`.
    Consequently the Christoffel function satisfies
    `λ_M(0) ≤ cosh (2 n G)⁻¹ ^ 2`: the germ-length blowup with the explicit
    rate, the theorem that discharged e1u VERIFIER target 6. The competitor is
    the Chebyshev polynomial `T_n` composed with the quadratic map sending the
    band onto `[-1, 1]`, normalized at `0`; `Polynomial.Chebyshev.T` carries
    the Mathlib side. -/
theorem v2_germ_bound (M : ℕ) (g T : ℝ) (hg : 0 < g) (hgT : g < T)
    (x w : Fin M → ℝ) (hx : ∀ j, g ≤ |x j| ∧ |x j| ≤ T)
    (hw : ∀ j, 0 ≤ w j) (hw1 : ∑ j, w j = 1) :
    ∃ P : Polynomial ℝ, P.natDegree ≤ M - 1 ∧ P.eval 0 = 1 ∧
      ∑ j, w j * P.eval (x j) ^ 2 ≤
        (Real.cosh (2 * (((M - 1) / 2 : ℕ) : ℝ) * bandGreen g T))⁻¹ ^ 2 := by
  -- #VQ-2: the competitor is `C V⁻¹ * (T_n).comp q` with `q` the quadratic
  -- band map and `V = T_n(q(0)) = cosh (2nG)`.
  set n : ℕ := (M - 1) / 2 with hn
  set V : ℝ := Real.cosh (2 * (n : ℝ) * bandGreen g T) with hV
  set D : ℝ := T ^ 2 - g ^ 2 with hD
  have hDpos : 0 < D := by rw [hD]; nlinarith
  set a : ℝ := (T ^ 2 + g ^ 2) / D with ha
  have ha1 : 1 ≤ a := by
    rw [ha, one_le_div hDpos, hD]
    nlinarith
  have hcosh : Real.cosh (arcoshReal a) = a := cosh_arcoshReal ha1
  -- the band Green's function is half the arcosh of `a`
  have hbandval : bandGreen g T = arcoshReal a / 2 := by
    unfold bandGreen
    rw [← hD, ← ha]
  -- the Chebyshev value at the center of the gap is exactly `V`
  have hVval : (Polynomial.Chebyshev.T ℝ (n : ℤ)).eval a = V := by
    conv_lhs => rw [← hcosh]
    rw [Polynomial.Chebyshev.T_real_cosh, hV, hbandval]
    push_cast
    congr 1
    ring
  have hV1 : 1 ≤ V := by rw [hV]; exact Real.one_le_cosh _
  have hVne : V ≠ 0 := (lt_of_lt_of_le one_pos hV1).ne'
  set q : Polynomial ℝ := Polynomial.C a + Polynomial.C (-2 / D) * Polynomial.X ^ 2 with hqdef
  refine ⟨Polynomial.C V⁻¹ * ((Polynomial.Chebyshev.T ℝ (n : ℤ)).comp q), ?_, ?_, ?_⟩
  · -- degree: `natDegree (C V⁻¹ * T_n.comp q) ≤ n * 2 ≤ M - 1`
    refine le_trans (Polynomial.natDegree_C_mul_le _ _)
      (le_trans Polynomial.natDegree_comp_le ?_)
    have hqdeg : q.natDegree ≤ 2 := by
      rw [hqdef]
      exact le_trans (Polynomial.natDegree_add_le _ _)
        (max_le (by simp) (Polynomial.natDegree_C_mul_X_pow_le _ 2))
    have hT : (Polynomial.Chebyshev.T ℝ (n : ℤ)).natDegree = n := by
      rw [Polynomial.Chebyshev.natDegree_T]
      exact Int.natAbs_natCast n
    rw [hT]
    calc n * q.natDegree ≤ n * 2 := Nat.mul_le_mul (le_refl n) hqdeg
      _ ≤ M - 1 := by omega
  · -- normalization at the origin: `q(0) = a` and `T_n(a) = V`
    have hq0 : q.eval 0 = a := by
      rw [hqdef]
      simp
    rw [Polynomial.eval_mul, Polynomial.eval_C, Polynomial.eval_comp, hq0, hVval,
      inv_mul_cancel₀ hVne]
  · -- the weighted square sum: each atom maps into `[-1, 1]` where `|T_n| ≤ 1`
    have hatom : ∀ j, ((Polynomial.Chebyshev.T ℝ (n : ℤ)).eval (q.eval (x j))) ^ 2 ≤ 1 := by
      intro j
      have h1 : g ^ 2 ≤ x j ^ 2 := by nlinarith [(hx j).1, abs_nonneg (x j), sq_abs (x j)]
      have h2 : x j ^ 2 ≤ T ^ 2 := by nlinarith [(hx j).2, abs_nonneg (x j), sq_abs (x j)]
      have heval : q.eval (x j) = (T ^ 2 + g ^ 2 - 2 * x j ^ 2) / D := by
        rw [hqdef]
        simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
          Polynomial.eval_C, Polynomial.eval_X, ha]
        ring
      have hlo : -1 ≤ q.eval (x j) := by
        rw [heval, le_div_iff₀ hDpos, hD]
        nlinarith
      have hhi : q.eval (x j) ≤ 1 := by
        rw [heval, div_le_one hDpos, hD]
        nlinarith
      obtain ⟨θ, hθ⟩ : ∃ θ, Real.cos θ = q.eval (x j) :=
        ⟨Real.arccos (q.eval (x j)), Real.cos_arccos hlo hhi⟩
      rw [← hθ, Polynomial.Chebyshev.T_real_cos]
      exact Real.cos_sq_le_one _
    have hterm : ∀ j,
        w j * (Polynomial.C V⁻¹ * ((Polynomial.Chebyshev.T ℝ (n : ℤ)).comp q)).eval (x j) ^ 2
          ≤ w j * V⁻¹ ^ 2 := by
      intro j
      refine mul_le_mul_of_nonneg_left ?_ (hw j)
      rw [Polynomial.eval_mul, Polynomial.eval_C, Polynomial.eval_comp, mul_pow]
      calc V⁻¹ ^ 2 * ((Polynomial.Chebyshev.T ℝ (n : ℤ)).eval (q.eval (x j))) ^ 2
          ≤ V⁻¹ ^ 2 * 1 := mul_le_mul_of_nonneg_left (hatom j) (sq_nonneg _)
        _ = V⁻¹ ^ 2 := mul_one _
    refine le_trans (Finset.sum_le_sum fun j _ => hterm j) ?_
    rw [← Finset.sum_mul, hw1, one_mul]

/-! ## #VQ-3: the nilpotent transfer atoms (e1u-2) -/

/-- The rank-one chain generator `J u uᵀ` of the Kac-Krein footprint
    construction, on explicit `2 × 2` matrices: `J = !![0, 1; -1, 0]` and
    `u uᵀ = !![u 0 * u 0, u 0 * u 1; u 1 * u 0, u 1 * u 1]`. -/
noncomputable def rankOneTransfer (u : Fin 2 → ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  !![(0 : ℝ), 1; -1, 0] * !![u 0 * u 0, u 0 * u 1; u 1 * u 0, u 1 * u 1]

/-- **#VQ-3a (e1u-2, nilpotency).** `(J u uᵀ) ^ 2 = 0`: the symplectic form
    vanishes on the diagonal (`uᵀ J u = 0`), so indivisible intervals have
    polynomial transfer of exactly degree one. One of the two matrix facts
    the whole e1u rung leans on. -/
theorem rankOneTransfer_sq (u : Fin 2 → ℝ) :
    rankOneTransfer u ^ 2 = 0 := by
  -- #VQ-3a: entrywise, every entry of the square cancels.
  rw [pow_two]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rankOneTransfer, Matrix.mul_apply, Fin.sum_univ_two] <;> ring

/-- **#VQ-3b (e1u-2, exact propagator).** The degree-one propagators along an
    indivisible interval compose additively in the length coordinate:
    `(1 + z • J u uᵀ) * (1 + z' • J u uᵀ) = 1 + (z + z') • J u uᵀ`.
    Immediate from #VQ-3a once elaborated. -/
theorem rankOneTransfer_propagator (u : Fin 2 → ℝ) (z z' : ℝ) :
    (1 + z • rankOneTransfer u) * (1 + z' • rankOneTransfer u) =
      1 + (z + z') • rankOneTransfer u := by
  -- #VQ-3b: expand and kill the cross term with the nilpotency #VQ-3a.
  have h : rankOneTransfer u * rankOneTransfer u = 0 := by
    have h2 := rankOneTransfer_sq u
    rwa [pow_two] at h2
  rw [add_mul, one_mul, mul_add, mul_one, smul_mul_smul_comm, h, smul_zero, add_zero, add_smul]
  abel

end ZetaRH.VerifierQueue
