-- Main module for the ZetaRH project. Imports all sub-modules.
-- See lean/README.md for project status and structure.

import ZetaRH.Basic
import ZetaRH.MathlibBridge
import ZetaRH.DavenportHeilbronn
import ZetaRH.KillCriteria
import ZetaRH.R3_5
import ZetaRH.LineRestriction
import ZetaRH.LambdaBlueprints
import ZetaRH.FrobeniusAlgebra
import ZetaRH.PrismaticCohomology
import ZetaRH.PrismaticFoliation
import ZetaRH.HodgeIndex
import ZetaRH.CurveSquareIntersection
import ZetaRH.IsogenyDegree
import ZetaRH.ArakelovAssembly
import ZetaRH.FunctionFieldRH
import ZetaRH.LocalFactor
import ZetaRH.FrobeniusExistence
import ZetaRH.TateModule
import ZetaRH.EulerSenLinearAlgebra
import ZetaRH.SenDefiniteObstruction
import ZetaRH.TraceBlindObstruction
import ZetaRH.ExplicitFormula
import ZetaRH.AccidentAudit
import ZetaRH.RHEquivalences
import ZetaRH.RiemannZetaConj
import ZetaRH.ArithmeticPolarization
import ZetaRH.DigammaExtras
import ZetaRH.CrystalCocycle
import ZetaRH.VT_NP1
import ZetaRH.ToyModel
import ZetaRH.SchurCohn
import ZetaRH.GaussLucas
import ZetaRH.GaussFloor
import ZetaRH.RationalRootFloor
import ZetaRH.ModelTheoreticFrobenius
import ZetaRH.TamenessTrade
import ZetaRH.BorgerVacuity
import ZetaRH.S4Carrier
